# This is an example using the nginx image to proxy requests to a fpm backend
version: '3.1'

services:
    fpm:
        image: xigen/php:fpm-7
    nginx:
        container_name: nginx
        image: xigen/nginx
        depends_on:
            - fpm
        ports:
            - "80:80"
            - "443:443"
