# This is an example using the nginx image to proxy requests to a fpm backend
version: '3.4'

services:
    fpm:
        image: xigen/php:fpm-73
    nginx:
        image: xigen/nginx
        depends_on:
            - fpm
        ports:
            - "80:80"
            - "443:443"